# Generated by Django 3.1.5 on 2021-01-28 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=200)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('isAllDayEvent', models.BooleanField(default=False)),
                ('tipo', models.CharField(default='comision', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LeyesEnTramitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, unique=True)),
                ('url', models.CharField(default='', max_length=300)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Senador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('created_at', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1000, unique=True)),
                ('url', models.TextField(default='', max_length=1000)),
                ('exp', models.CharField(default='', max_length=50)),
                ('comision_global', models.CharField(default='', max_length=100)),
                ('discurso', models.FileField(blank=True, null=True, upload_to='discursos')),
                ('comision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comision')),
            ],
        ),
        migrations.CreateModel(
            name='Enmienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Plantilla', max_length=500, unique=True)),
                ('url', models.TextField(default='')),
                ('mocion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mocion')),
            ],
        ),
        migrations.AddField(
            model_name='comision',
            name='evento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
        migrations.AddField(
            model_name='comision',
            name='senador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.senador'),
        ),
    ]
