# Generated by Django 3.1.5 on 2021-02-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocion',
            name='voto',
            field=models.IntegerField(default=1),
        ),
    ]
