# Generated by Django 3.1.5 on 2021-02-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mocion_voto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocion',
            name='pdf',
            field=models.TextField(default=''),
        ),
    ]
