# Generated by Django 3.1.5 on 2021-02-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mocion_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leyesentramitacion',
            name='name',
            field=models.TextField(default='', unique=True),
        ),
    ]
