# Generated by Django 3.1.5 on 2021-03-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210303_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='leyesentramitacion',
            name='defensa',
            field=models.FileField(blank=True, null=True, upload_to='leyes'),
        ),
        migrations.AddField(
            model_name='leyesentramitacion',
            name='enmiendas_doc',
            field=models.FileField(blank=True, null=True, upload_to='leyes'),
        ),
        migrations.AddField(
            model_name='leyesentramitacion',
            name='veto',
            field=models.FileField(blank=True, null=True, upload_to='leyes'),
        ),
        migrations.AddField(
            model_name='leyesentramitacion',
            name='voto',
            field=models.IntegerField(default=1),
        ),
    ]
